In [2]:
import numpy as np
import pandas as pd
import gzip
import datetime
import seaborn as sns

In [3]:
def parseData(fname):
  for l in open(fname):
    yield eval(l)

In [26]:
gamesMeta = pd.read_json('/kaggle/input/game-recommendations-on-steam/games_metadata.json', lines = True)

In [27]:
gamesMeta

,app_id,description,tags
0,13500,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre..."
1,22364,,[Action]
2,113020,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St..."
3,226560,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P..."
4,249050,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra..."
...,...,...,...
50867,2296380,,[]
50868,1272080,,[]
50869,1402110,,[]
50870,2272250,Embark on a journey into the darkest nightmare...,"[Early Access, FPS, Action, Retro, First-Perso..."
50871,2488510,,[]

In [5]:
games = pd.read_csv('/kaggle/input/game-recommendations-on-steam/games.csv')

In [6]:
games

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0.0,True
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0.0,True
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0.0,True
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50867,2296380,I Expect You To Die 3: Cog in the Machine,2023-09-28,True,False,False,Very Positive,96,101,22.00,0.00,0.0,True
50868,1272080,PAYDAY 3,2023-09-21,True,False,False,Mostly Negative,38,29458,40.00,0.00,0.0,True
50869,1402110,Eternights,2023-09-11,True,False,False,Very Positive,89,1128,30.00,0.00,0.0,True
50870,2272250,Forgive Me Father 2,2023-10-19,True,False,False,Very Positive,95,82,17.00,0.00,0.0,True
50871,2488510,FatalZone,2023-10-23,True,False,False,Very Positive,88,144,4.00,0.00,0.0,True

In [22]:
gamesData = games.to_dict('records')

In [23]:
gamesData[0]

{'app_id': 13500,
 'title': 'Prince of Persia: Warrior Within™',
 'date_release': '2008-11-21',
 'win': True,
 'mac': False,
 'linux': False,
 'rating': 'Very Positive',
 'positive_ratio': 84,
 'user_reviews': 2199,
 'price_final': 9.99,
 'price_original': 9.99,
 'discount': 0.0,
 'steam_deck': True}

In [3]:
interactions = pd.read_csv('/kaggle/input/game-recommendations-on-steam/recommendations.csv')

In [7]:
interactions_df = interactions.merge(games, on = ['app_id'])

In [10]:
interactions_df

,app_id,helpful,funny,date,is_recommended,hours,user_id,review_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,975370,0,0,2022-12-12,True,36.3,49625,0,Dwarf Fortress,2022-12-06,True,False,False,Overwhelmingly Positive,95,19665,30.00,0.00,0.0,True
1,975370,0,0,2022-12-22,True,24.3,11722481,226,Dwarf Fortress,2022-12-06,True,False,False,Overwhelmingly Positive,95,19665,30.00,0.00,0.0,True
2,975370,3,0,2022-12-07,True,177.0,10786201,316,Dwarf Fortress,2022-12-06,True,False,False,Overwhelmingly Positive,95,19665,30.00,0.00,0.0,True
3,975370,5,0,2022-12-12,True,388.6,8460981,1182,Dwarf Fortress,2022-12-06,True,False,False,Overwhelmingly Positive,95,19665,30.00,0.00,0.0,True
4,975370,0,0,2022-12-07,True,70.1,12438583,1346,Dwarf Fortress,2022-12-06,True,False,False,Overwhelmingly Positive,95,19665,30.00,0.00,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38354096,1238180,6,0,2021-06-02,True,2.9,9782801,38310856,My Universe - School Teacher,2020-11-18,True,True,False,Mixed,50,10,29.99,29.99,0.0,True
38354097,940920,0,0,2020-12-27,True,1.1,8903934,38314166,BlastFX,2018-10-05,True,True,True,Positive,90,10,19.99,19.99,0.0,True
38354098,1968790,8,0,2022-11-11,True,8.7,11704920,38322423,Alkali,2022-11-10,True,False,False,Positive,100,14,11.99,11.99,0.0,True
38354099,1400260,11,0,2020-09-11,True,420.0,9406610,38333991,Legendary Journeys,2020-09-07,True,False,False,Positive,95,20,11.99,11.99,0.0,True
38354100,2023440,0,0,2022-10-16,True,28.3,4677991,38344279,Jettatura,2022-10-15,True,False,True,Positive,92,14,19.99,19.99,0.0,True

In [11]:
df2 = interactions_df[['user_id', 'app_id', 'is_recommended', 'hours', 'date',
                       'price_original', 'price_final', 'title', 'date_release',
                       'rating', 'positive_ratio', 'user_reviews']]

df3 = df2.rename(columns = {'user_id': 'userID', 'app_id': 'gameID', 'is_recommended': 'recommended',
                            'hours': 'hours_played', 'date': 'review_date', 'date_release': 'release_date',
                            'rating': 'overall_rating'})

In [13]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38354101 entries, 0 to 38354100
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   userID          int64
 1   gameID          int64
 2   recommended     bool
 3   hours_played    float64
 4   review_date     object
 5   price_original  float64
 6   price_final     float64
 7   title           object
 8   release_date    object
 9   overall_rating  object
 10  positive_ratio  int64
 11  user_reviews    int64
dtypes: bool(1), float64(3), int64(4), object(4)
memory usage: 3.2+ GB

In [25]:
df3['title'] = df3['title'].astype('string')
df3['overall_rating'] = df3['overall_rating'].astype('category')
df3['release_date'] = pd.to_datetime(df3['release_date'], format = '%Y-%m-%d')
df3['review_date'] = pd.to_datetime(df3['review_date'], format = '%Y-%m-%d')

In [26]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38354101 entries, 0 to 38354100
Data columns (total 12 columns):
 #   Column          Dtype
---  ------          -----
 0   userID          int64
 1   gameID          int64
 2   recommended     bool
 3   hours_played    float64
 4   review_date     datetime64[ns]
 5   price_original  float64
 6   price_final     float64
 7   title           string
 8   release_date    datetime64[ns]
 9   overall_rating  category
 10  positive_ratio  int64
 11  user_reviews    int64
dtypes: bool(1), category(1), datetime64[ns](2), float64(3), int64(4), string(1)
memory usage: 2.9 GB